<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>URL Shortener</title>
  <link rel="shortcut icon" href="/assets/images/favicon.ico" type="image/x-icon">
  <meta name="description" content="Shorten URLs with PHPEnalva">
  <meta name="author" content="Yan Brasiliano Silva Penalva">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="/assets/css/style.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/">PHP<span class="brand-color">enalva URL Shortener</span></a>
    </div>
  </nav>

  <div class="container mt-5 text-center">
    <h1 class="display-4">PHPenalva URL Shortener</h1>
    <p class="lead mb-4">Quickly shorten your URLs with ease.</p>

    <div class="row justify-content-center">
      <div class="col-md-8">
        <form>
          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Enter URL here" aria-label="URL">
            <button class="btn btn-outline-secondary" type="submit">Shorten</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <footer class="footer bg-light mt-5 py-3">
    <div class="container text-center">
      <span class="text-muted">Powered with PHPenalva. All rights reserved.</span>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>

</html>